name: ts-anomaly-detection
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tensorflow
  - pytorch
  - torchvision
  - tqdm
  - jupyter
  - pyyaml
  - scipy
  - statsmodels
  - conda-forge::graphviz
  - conda-forge::pydot
  - pip
  - pip:
      - wandb
      - opencv-python
      - requests
      - diffusers
      - transformers